---
clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      tags: true
    when:
      event:
        - manual
        - pull_request
        - push

labels:
  location: sof.bg

matrix:
  include:
    - distro: centos
      distro_version: 7
      flavour: rpm
    - distro: debian
      distro_version: 10
      flavour: deb
    - distro: debian
      distro_version: 11
      flavour: deb
    - distro: debian
      distro_version: 12
      flavour: deb
    - distro: debian
      distro_version: 13
      flavour: deb
    - distro: ubuntu
      distro_version: 18.04
      flavour: deb
    - distro: ubuntu
      distro_version: 20.04
      flavour: deb
    - distro: ubuntu
      distro_version: 22.04
      flavour: deb
    - distro: ubuntu
      distro_version: 24.04
      flavour: deb

steps:
  build_deb:
    image: ${distro}:${distro_version}
    environment:
      DEBIAN_FRONTEND: noninteractive
    commands:
      - grep -q buster /etc/apt/sources.list && sed -i 's|^deb http://deb.debian.org|deb http://archive.debian.org|' /etc/apt/sources.list
      - mkdir /etc/apt.conf.d
      - printf 'Acquire::Retries "3";' > /etc/apt.conf.d/99retries
      - apt-get update
      - apt-get -yy --no-install-recommends install build-essential cmake file git libipset-dev libmosquitto-dev libnftnl-dev libssl-dev pkg-config
      - cmake -DUSE_BACKEND=nftables .
      - cpack -G DEB
      - apt -yy install ./build/*.deb
    when:
      event:
        - manual
        - pull_request
        - push
      matrix:
        flavour: deb

  build_rpm:
    image: ${distro}:${distro_version}
    commands:
      - sed -i 's|^mirrorlist|#mirrorlist|' /etc/yum.repos.d/CentOS-Base.repo
      - sed -i 's|^#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|' /etc/yum.repos.d/CentOS-Base.repo
      - yum -y install epel-release
      - yum -y install cmake3 ipset-devel libnftnl-devel make mosquitto-devel openssl-devel pkgconfig '@Development Tools'
      - cmake3 -DUSE_BACKEND=nftables .
      - cpack3 -G RPM
      - yum -y localinstall ./build/*.rpm
    when:
      event:
        - manual
        - pull_request
        - push
      matrix:
        flavour: rpm

depends_on:
  - test_debug
