variables:
  - &container_image 'alpine:3.22'

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      tags: true
    when:
      event:
        - manual
        - pull_request
        - push

steps:
  clang_format:
    image: *container_image
    commands:
      - apk add --no-cache clang20-extra-tools
      - clang-format --Werror --dry-run src/*.c src/*.h
    when:
      event:
        - manual
        - pull_request
        - push

