---
# explicit clone with conditional
clone:
  git:
    image: woodpeckerci/plugin-git
    when:
      event: tag

pipeline:
  gitea_release:
    image: plugins/gitea-release
    settings:
      api_key:
        from_secret: gitea_password
      base_url:
        from_secret: gitea_url
    when:
      event: tag
